[custom]
;不要随意改变关键字，否则会导致出错
;acl4SSR规则-在线更新版
;20240413-结合ACL4SSR_Online_Full.ini规则，添加标志：OpenAi
;20240413-结合ACL4SSR_Online_Full.ini规则，添加分组：狮城.台湾.韩国，CF（域名DN，无密NOTLS，有密TLS）
;20240413-改变顺序.x10:美国.狮城.香港.台湾.日本.韩国.域名.无秘.有秘
;20240420-增加泛播
;20240421-台湾变更为优选，国家分组前添加机场代码识别，变更测速网址
;20240425-减少组别，删除香港（不支持Bard），韩国
;20240706-恢复组别，香港，相关节点测速延迟较低
;🇰🇷 韩国`[]
;custom_proxy_group=🇰🇷 韩国`url-test`(ICN|KR|Korea|KOR|首尔|韩|韓)`http://www.google-analytics.com/generate_204`300,,50

;去广告：支持
;自动测速：支持
;微软分流：支持
;苹果分流：支持
;增强中国IP段：不支持
;增强国外GFW：不支持
;多国家分组：支持港/日/美

ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/LocalAreaNetwork.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/UnBan.list
ruleset=🛑 全球拦截,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanAD.list
ruleset=🍃 应用净化,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/BanProgramAD.list
ruleset=📢 谷歌FCM,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/GoogleFCM.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/GoogleCN.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/SteamCN.list
ruleset=Ⓜ️ 微软服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Microsoft.list
ruleset=🍎 苹果服务,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Apple.list
ruleset=📲 电报信息,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Telegram.list
ruleset=💬 OpenAI,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/Ruleset/OpenAi.list
ruleset=🌍 国外媒体,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyMedia.list
ruleset=🚀 节点选择,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ProxyLite.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaDomain.list
ruleset=🎯 全球直连,https://raw.githubusercontent.com/ACL4SSR/ACL4SSR/master/Clash/ChinaCompanyIp.list
;ruleset=🎯 全球直连,[]GEOIP,LAN
ruleset=🎯 全球直连,[]GEOIP,CN
ruleset=🐟 漏网之鱼,[]FINAL

custom_proxy_group=🚀 节点选择`select`[]♻️ 自动选择`[]🇹🇼 优选`[]🇺🇲 美国`[]🇭🇰 香港`[]🇸🇬 狮城`[]🇯🇵 日本`[]🇲🇲 泛播`[]🇨🇨 域名`[]🇸🇳 无秘`[]🇸🇷 有秘`[]🚀 手动切换`[]DIRECT
custom_proxy_group=🚀 手动切换`select`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.google-analytics.com/generate_204`300,,50
custom_proxy_group=🌍 国外媒体`select`[]🚀 节点选择`[]♻️ 自动选择`[]🎯 全球直连`.*
custom_proxy_group=📲 电报信息`select`[]🚀 节点选择`[]🎯 全球直连`.*
custom_proxy_group=💬 OpenAI`select`[]🚀 节点选择`[]🎯 全球直连`.*
custom_proxy_group=Ⓜ️ 微软服务`select`[]🚀 节点选择`[]🎯 全球直连`.*
custom_proxy_group=🍎 苹果服务`select`[]🚀 节点选择`[]🎯 全球直连`.*
custom_proxy_group=📢 谷歌FCM`select`[]🚀 节点选择`[]🎯 全球直连`[]♻️ 自动选择`.*
custom_proxy_group=🎯 全球直连`select`[]DIRECT`[]🚀 节点选择`[]♻️ 自动选择
custom_proxy_group=🛑 全球拦截`select`[]REJECT`[]DIRECT
custom_proxy_group=🍃 应用净化`select`[]REJECT`[]DIRECT
custom_proxy_group=🐟 漏网之鱼`select`[]🎯 全球直连`[]🚀 节点选择`[]♻️ 自动选择`.*

custom_proxy_group=🇹🇼 优选`url-test`(官方|优选|电信|移动|联通|KHH|TPE|台|新北|彰化|TW|Taiwan)`http://www.google-analytics.com/generate_204`300,,50
custom_proxy_group=🇺🇲 美国`url-test`(SEA|LAX|SJC|Default|美|波特兰|达拉斯|俄勒冈|凤凰城|费利蒙|硅谷|拉斯维加斯|洛杉矶|圣何塞|圣克拉拉|西雅图|芝加哥|US|United States)`http://www.google-analytics.com/generate_204`300,,150
custom_proxy_group=🇭🇰 香港`url-test`(HKG|港|HK|hk|Hong Kong|HongKong|hongkong)`http://www.google-analytics.com/generate_204`600,,50
custom_proxy_group=🇸🇬 狮城`url-test`(SIN|新加坡|坡|狮城|SG|Singapore)`http://www.google-analytics.com/generate_204`300,,50
custom_proxy_group=🇯🇵 日本`url-test`(FUK|OKA|KIX|NRT|日本|川日|东京|大阪|泉日|埼玉|沪日|深日|[^-]日|JP|Japan)`http://www.google-analytics.com/generate_204`300,,50
custom_proxy_group=🇲🇲 泛播`url-test`(泛播|CF|cf)`http://www.google-analytics.com/generate_204`300,,50
custom_proxy_group=🇨🇨 域名`url-test`(域名|DN|dn)`http://www.google-analytics.com/generate_204`300,,50
custom_proxy_group=🇸🇳 无秘`url-test`(无秘|NT|nt)`http://www.google-analytics.com/generate_204`300,,50
custom_proxy_group=🇸🇷 有秘`url-test`(有秘|YT|yt)`http://www.google-analytics.com/generate_204`300,,50


enable_rule_generator=true
overwrite_original_rules=true